[package]
name = "cargo-up"
version = "0.0.1"
authors = ["Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"]
edition = "2018"
description = "Upgrade your dependencies by automatically fixing your code"
repository = "https://github.com/pksunkara/cargo-up"
license = "MIT"

[[bin]]
name = "cargo-up"
path = "src/cli/main.rs"
required-features = ["cli"] # remove the need for this

[lib]
name = "cargo_up"
path = "src/lib/mod.rs"

[dependencies]
# required by lib and bin
semver = "0.9"
lazy_static = "1.4"
console = "0.11"

# required by lib
cargo-up-derive = { path = "./cargo-up-derive", version = "0.0.1", optional = true }
ra_ide_db = { path = "../../rust-analyzer/crates/ra_ide_db", optional = true }
ra_syntax = { path = "../../rust-analyzer/crates/ra_syntax", optional = true }
ra_hir = { path = "../../rust-analyzer/crates/ra_hir", optional = true }
ra_text_edit = { path = "../../rust-analyzer/crates/ra_text_edit", optional = true }
ra_db = { path = "../../rust-analyzer/crates/ra_db", optional = true }
rust-analyzer = { path = "../../rust-analyzer/crates/rust-analyzer", optional = true }

# required by bin
clap = { version = "=3.0.0-beta.1", optional = true }
cargo_metadata = { version = "0.9", optional = true }
thiserror = { version = "1.0", optional = true }
heck = { version = "0.3", optional = true }
crates_io_api = { version = "0.5", optional = true } # TODO: 0.6 async or replace with pure reqwest

[profile.release]
lto = "thin"

[features]
default = ["lib"]
lib = [
	"cargo-up-derive",
	"ra_ide_db",
	"ra_syntax",
	"ra_hir",
	"ra_text_edit",
	"ra_db",
	"rust-analyzer"
]
cli = [
	"clap",
	"cargo_metadata",
	"thiserror",
	"heck",
	"crates_io_api"
]
docs = []

[workspace]
members = [
	"cargo-up-derive",
	"cargo-up-up",
	"rust-up",
]
