[package]
name = "cargo-up"
version = "0.0.1"
authors = ["Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"]
edition = "2018"
description = "Upgrade your dependencies by automatically fixing your code"
repository = "https://github.com/pksunkara/cargo-up"
readme = "README.md"
license = "MIT"

[[bin]]
name = "cargo-up"
path = "src/main.rs"
required-features = ["build-binary"]

[lib]
name = "cargo_up"
path = "src/lib.rs"

[dependencies]
clap = { version = "=3.0.0-beta.1", optional = true }
log = "0.4"
env_logger = "0.7"
cargo_metadata = "0.9"
# rust-analyzer = { path = "../../rust-analyzer/crates/rust-analyzer" }
# ra_db = { path = "../../rust-analyzer/crates/ra_db" }
# ra_ide_db = { path = "../../rust-analyzer/crates/ra_ide_db" }
# ra_syntax = { path = "../../rust-analyzer/crates/ra_syntax" }
# ra_hir = { path = "../../rust-analyzer/crates/ra_hir" }
# ra_text_edit = { path = "../../rust-analyzer/crates/ra_text_edit" }

[profile.release]
lto = "thin"

[features]
default = []
build-binary = ["clap"]
build-docs = []

[workspace]
members = [
	"cargo-up-derive",
	"cargo-up-up",
	"rust-up",
]
