[package]
name = "cargo-up"
version = "0.0.1"
authors = ["Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"]
edition = "2018"
description = "Upgrade your dependencies by automatically fixing your code"
repository = "https://github.com/pksunkara/cargo-up"
license = "MIT"

[[bin]]
name = "cargo-up"
path = "src/cli/main.rs"
required-features = ["build-binary"]
default-features = false

[lib]
name = "cargo_up"
path = "src/lib/mod.rs"

[dependencies]
# required by lib and bin
log = "0.4"
cargo_metadata = "0.9"
cargo-up-utils = { path = "./cargo-up-utils", version = "0.0.0" }

# ????
rust-analyzer = { path = "../../rust-analyzer/crates/rust-analyzer" }
ra_db = { path = "../../rust-analyzer/crates/ra_db" }

# required by lib
cargo-up-derive = { path = "./cargo-up-derive", version = "0.0.1", optional = true }
ra_ide_db = { path = "../../rust-analyzer/crates/ra_ide_db", optional = true }
ra_syntax = { path = "../../rust-analyzer/crates/ra_syntax", optional = true }
ra_hir = { path = "../../rust-analyzer/crates/ra_hir", optional = true }
ra_text_edit = { path = "../../rust-analyzer/crates/ra_text_edit", optional = true }

# required by bin
clap = { version = "=3.0.0-beta.1", optional = true }
env_logger = { version = "0.7", optional = true }
lazy_static = { version = "1.4", optional = true }
console = { version = "0.11", optional = true }

[profile.release]
lto = "thin"

[features]
default = ["build-lib"]
build-lib = ["cargo-up-derive", "ra_ide_db", "ra_syntax", "ra_hir", "ra_text_edit"]
build-binary = ["clap", "env_logger", "lazy_static", "console"]
build-docs = []

[workspace]
members = [
	"cargo-up-derive",
	"cargo-up-utils",
	"cargo-up-runner",
	"cargo-up-up",
	"rust-up",
]
