[package]
name = "cargo-up-up"
version = "0.0.1"
authors = ["Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"]
edition = "2018"
description = "Automatic updater for cargo-up library"
repository = "https://github.com/pksunkara/cargo-up"
license = "MIT"

[dependencies]
